port: 9090
adapter:
  - id: goagentx
    type: HTTP
    host: 127.0.0.1
    port: 8016
  - id: speed
    type: SPEED
    adapter:
      - goagentx
      - direct
rule:
  - type: country
    country: CN
    match: true
    adapter: direct
  - type: all
    adapter: speed
